workflows:
  build:
    scripts:
      - name: Set execute permissions for gradlew
        script: chmod +x gradlew
      - name: Set JAVA_HOME
        script: |
          echo "export JAVA_HOME=/usr/lib/jvm/java-1.17.0-openjdk-amd64" >> $GITHUB_ENV
      - name: Build Android release
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
